### ISSUE TITLE
.NET Requirement is faulty

### ISSUE THREAD

**Issue by Glamurio** [ValentinoAbate/Pokemon-Randomizer#1] opened 2023-01-08 21:35 UTC
Hey, so, I was excited to try this out for the first time, but it turns out it doesn't want to run at all.

Running "ProceduralPokemonRandomizer.exe" just causes the program to prompt me to install .NET, which I have uninstalled and re-installed several times now.

I'm guessing it's safe to say that you don't have that issue on your system so this is entirely news to you.

I'm running Windows 11, was using .NET 4.8, am now on .NET 4.8.1, though it was working with neither version.

**Comment by ValentinoAbate** [comment] 2023-02-18 02:50
Thanks for letting me know! 

I've built the latest release [v1.0-beta.7](https://github.com/ValentinoAbate/Pokemon-Randomizer/releases/tag/v1.0-beta.7) as a standalone application which should remove the dependency and fix the issue

I will close this issue as fixed in v1.0-beta.7+, but as you guessed I am unable to reproduce the issue you described on my system so please reopen the issue if you try running v1.0-beta.7 and are still having the same problem!

**Closed as completed by ValentinoAbate** 2023-02-18 02:50 UTC
